declare module 'screenshotmachine' {  interface ScreenshotOptions {
    url: string;
    dimension?: string;
    device?: string;
    format?: string;
    cacheLimit?: string;
    delay?: string;
    zoom?: string;
    [key: string]: any;
  }

  /**
   * Generate the API URL for Screenshot Machine
   * @param customerKey Your Screenshot Machine customer key
   * @param secretPhrase Secret phrase (optional)
   * @param options Screenshot options
   * @returns The generated API URL
   */
  export function generateScreenshotApiUrl(
    customerKey: string, 
    secretPhrase: string, 
    options: ScreenshotOptions
  ): string;

  /**
   * Read screenshot from the API
   * @param apiUrl The API URL generated by generateScreenshotApiUrl
   * @returns A readable stream containing the screenshot data
   */
  export function readScreenshot(apiUrl: string): NodeJS.ReadableStream;
}
